import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    generate: 'Generate',
    garments: 'Garments',
    gallery: 'Gallery',
    models: 'Models',
    templates: 'Templates',
    training: 'Training',

    // Auth
    login: 'Login',
    logout: 'Logout',
    upgradePlan: 'Upgrade Plan',

    // Common
    images: 'images',
    language: 'Language',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    continue: 'Continue',
    download: 'Download',
    upload: 'Upload',
    loading: 'Loading',

    // Upload page
    generateProductImage: 'Generate Product Image',
    aiDrivenModelPhotography: 'AI-driven model photography',
    simple: 'Simple',
    batch: 'Batch',
    style: 'Style',
    expert: 'Expert',
    uploadGarment: 'Upload garment',
    garmentInformation: 'Garment information',
    brandStyle: 'Brand style',
    selectModel: 'Select model',
    selectEnvironment: 'Select environment',
    customPrompt: 'Custom prompt',
    aiAnalyzing: 'AI analyzing garment...',
    aiSuggestions: 'AI suggestions',
    name: 'Name',
    category: 'Category',
    brand: 'Brand',
    sku: 'SKU / Article number',
    optional: 'Optional',
    selectCategory: 'Select category',
    tops: 'Tops',
    bottoms: 'Bottoms',
    dresses: 'Dresses',
    outerwear: 'Outerwear',
    accessories: 'Accessories',
    selectBrandStyle: 'Select brand style',
    none: 'None (default)',
    useEnvironmentFromSeed: 'Use seed environment',
    gender: 'Gender',
    female: 'Female',
    male: 'Male',
    orSelectSpecificModel: 'Or select specific model',
    studio: 'Studio',
    studioLighting: 'Studio lighting, light grey background',
    stockholm: 'Stockholm',
    stockholmStreets: 'Streets in Stockholm',
    custom: 'Custom',
    describeEnvironment: 'Describe the environment',
    generateImage: 'Generate image',
    saveAsTemplate: 'Save as template',

    // Gallery
    noImagesYet: 'No images generated yet',
    uploadGarmentAndGenerate: 'Upload a garment and generate your first image',
    selectMultiple: 'Select multiple',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    downloadSelected: 'Download',
    deleteSelected: 'Delete',
    generationInfo: 'Generation information',
    originalGarment: 'Original garment',
    generationSettings: 'Generation settings',
    model: 'Model',
    environment: 'Environment',
    promptUsed: 'Prompt used',
    imageLink: 'Image link',
    editImage: 'Edit image',
    deleteImage: 'Delete image',
    deleteSelectedImages: 'Delete selected images',
    deleteImageConfirm: 'Are you sure you want to delete this image? This action cannot be undone.',
    deleteImagesConfirm: 'Are you sure you want to delete {count} images? This action cannot be undone.',
    selectedOf: '{selected} selected of {total}',
    generatedImages: 'generated images',
    generating: 'Generating',
    comingSoon: 'Coming soon...',
    unknownGarment: 'Unknown garment',
    created: 'Created',
    status: 'Status',
    openOriginalImage: 'Open original image in new window →',
    garmentsInOutfit: 'Garments in outfit',
    styleDescription: 'Style description',
    aiAnalyzingStyleGallery: 'AI analyzing style...',
    aiAnalysisProductDescription: 'AI analysis (Product description)',
    copyProductText: 'Copy product text',
    styleLabel: 'Style',

    // Dashboard
    onePhotoIn: 'One photo in. Every asset out.',
    createProfessionalImages: 'Create professional model images in seconds.',
    getStarted: 'Get started',
    totalGarments: 'Garments',
    generated: 'Generated',
    thisWeek: 'This week',
    recentGenerated: 'Recent generated',
    recentGarments: 'Recent garments',
    recentModels: 'Recent models',
    viewAll: 'View all',
    woman: 'Woman',
    man: 'Man',
    neutral: 'Neutral',

    // Garments
    myGarments: 'My garments',
    uploadNew: 'Upload new',
    searchGarments: 'Search by name, brand or SKU...',
    noGarmentsYet: 'No garments yet',
    noMatchingGarments: 'No matching garments',
    tryDifferentSearch: 'Try a different search',
    uploadFirstGarment: 'Upload your first garment to get started',
    garmentsTotal: 'garments total',
    deleteGarment: 'Delete garment',
    deleteGarmentConfirm: 'Are you sure you want to delete this garment? This action cannot be undone.',
    information: 'Information',
    garmentInformationTitle: 'Garment information',
    aiDescription: 'AI Description',
    noAiDescription: 'No AI description available',
    editInformation: 'Edit information',

    // Models
    modelArchive: 'Model Archive',
    savedModels: 'saved models',
    createModel: 'Create model',
    create: 'Create',
    yourCreatedModels: 'Your created models',
    modelsOf: '{filtered} of {total} models',
    filters: 'Filters',
    searchModelName: 'Search by model name...',
    all: 'All',
    ethnicity: 'Ethnicity',
    caucasian: 'Caucasian',
    african: 'African',
    asian: 'Asian',
    hispanic: 'Hispanic',
    middleEastern: 'Middle Eastern',
    mixed: 'Mixed',
    noModelsMatch: 'No models match your filters',
    years: 'years',
    close: 'Close',
    deleteModel: 'Delete model',
    deleteModelConfirm: 'Are you sure you want to delete this model? This action cannot be undone.',

    // AI Styling
    aiStyling: 'AI Styling',
    selectGarmentsManually: 'Select garments manually',
    selectOutfit: 'Select outfit',
    letAiSuggestCombinations: 'Let AI suggest garment combinations that go well together',
    analyzing: 'Analyzing...',
    getSuggestions: 'Get suggestions',
    aiWillSuggestOutfits: 'AI will suggest outfits that match this brand identity',
    analyzingYourGarments: 'Analyzing your garments...',
    aiCreatingCombinations: 'AI creating perfect outfit combinations',
    suggestionsFromAi: 'Suggestions from AI:',
    addForCompleteOutfit: 'Add for complete outfit:',
    outfitSelected: 'Outfit selected:',
    garmentsSelectedGenerateDirectly: 'garments selected. Generate directly or continue to model selection.',
    cancelSelection: 'Cancel selection',
    getNewSuggestions: 'Get new suggestions',
    readyToStartStyling: 'Ready to start styling?',
    clickGetSuggestionsToAnalyze: 'Click "Get suggestions" and AI will analyze your garments and create perfect combinations',
    addAtLeast2Garments: 'Add at least 2 garments to use AI Stylist',

    // Batch
    selectGarmentsForBatch: 'Select garments for batch generation',
    selectMultipleGarments: 'Select multiple garments to generate images simultaneously',
    garmentsSelected: 'garments selected',
    existingBatchJobs: 'Existing batch jobs',
    createBatchJob: 'Create batch job',

    // Description language
    descriptionLanguage: 'Description language',
    generateInEnglish: 'Generate in English',
    generateInSwedish: 'Generate in Swedish',

    // Landing page
    aiGeneratedModels: 'AI-generated models',
    forProfessionalEcommerce: 'for professional e-commerce',
    heylookHelpsModern: 'HeyLook helps modern e-commerce companies create authentic, professional product images at scale. Give your team creative freedom, consistency and full control.',
    bookDemo: 'Book demo',
    trustedByLeading: 'Trusted by leading e-commerce companies',
    realBrandsRealResults: 'Real brands, real results',
    seeHowAiModels: 'See how AI-generated models make a difference for e-commerce companies',
    seeTheTransformation: 'See the transformation',
    fromGarmentToProfessional: 'From garment to professional product image in seconds',
    createYourOwnUniqueModels: 'Create your own unique models',
    generateAiModels: 'Generate AI models that perfectly match your brand. Customize age, ethnicity, body style and more.',
    createYourModels: 'Create your models',
    transformPhotoshoots: 'Transform photoshoots with AI models',
    createHighQuality: 'Create high-quality fashion images with AI models. Polished results, seamless workflow and a team ready to guide every step.',
    spendLessProduceMore: 'Spend less, produce more',
    createStudioQuality: 'Create studio-quality fashion images without increasing budget. AI models give you the same professional look, without production costs.',
    lowerProductionCosts: 'Lower production costs and save thousands with HeyLook AI',
    fasterToMarket: 'Faster to market',
    accelerateProduction: 'Accelerate production cycles and deliver new collections in days. Fashion teams can now update looks, refresh images and move faster than ever.',
    shorterProduction: 'Shorter production time from 6 weeks to 24 hours',
    inclusiveFromStart: 'Inclusive from start',
    showDiversity: 'Show diversity with AI models - different skin tones, body types and styles - so your images reflect real customers, everywhere.',
    increasedCTR: 'Increased CTR by using diverse models to reach more customers',
    testimonialQuote: 'Since we started using HeyLook, we can finally focus on creativity instead of coordination and work with the seamless flexibility that modern e-commerce requires.',
    creativeDirector: 'Creative Director, Nordic Fashion',
    timeSavings: 'Time savings',
    higherConversion: 'Higher conversion',
    alwaysAvailable: 'Always available',
    transformPhotoshootsGetResults: 'Transform photoshoots and get flawless results in no time',
    startCreatingToday: 'Start creating professional AI-generated product images today',

    // FileDropzone
    dragAndDropOrClick: 'Drag and drop or click',
    toSelectImage: 'to select an image',
    takePhotoWithCamera: 'Take photo with camera',
    uploading: 'Uploading...',

    // Footer
    aiDrivenProductPhotography: 'AI-driven product photography for e-commerce',
    product: 'Product',
    company: 'Company',
    aboutUs: 'About us',
    contact: 'Contact',
    careers: 'Careers',
    legal: 'Legal',
    privacyPolicy: 'Privacy policy',
    termsOfService: 'Terms of service',
    cookies: 'Cookies',
    allRightsReserved: 'All rights reserved.',

    // Training
    trainCustomModels: 'Train custom AI models',
    uploadImagesToTeach: 'Upload images to teach AI specific poses or styles',
    newModel: 'New model',
    poseTraining: 'Pose training',
    learnSpecificPoses: 'Teach AI specific poses by uploading 5-10 images with the same pose',
    styleTraining: 'Style training',
    createConsistentAesthetic: 'Create consistent aesthetic with images sharing the same visual style',
    composition: 'Composition',
    learnLayoutComposition: 'Teach AI layout and compositions from your reference images',
    noTrainedModels: 'No trained models yet',
    createFirstCustomModel: 'Create your first custom AI model',
    trainingImages: 'Training images',
    uploaded: 'uploaded',
    clickToSelectImages: 'Click to select images',
    orDragAndDrop: 'or drag and drop',
    tipsForBestResults: 'Tips for best results:',
    useSimilarLighting: 'Use images with similar lighting and quality',
    forPoseTraining: 'For pose training: same pose but different models/clothes',
    forStyleTraining: 'For style training: different subjects but same aesthetic',
    minImagesRecommended: 'At least 5 images recommended, 10+ is optimal',
    startTraining: 'Start training',
    startingTraining: 'Starting training...',
    useModel: 'Use model',
    deleteModelTraining: 'Delete model',
    deleteTrainedModelConfirm: 'Are you sure you want to delete this trained model? This action cannot be undone.',
    trainNewModel: 'Train new model',
    type: 'Type',
    pose: 'Pose',
    description: 'Description',
    whatShouldLearn: 'What should this model learn?',
    trainingPromptOptional: 'Training prompt (optional)',
    atLeast3Recommended: 'at least 3, recommended 5-10',
    moreImages: 'more images',
    uses: 'uses',

    // Templates
    templatesAndSeeds: 'Templates & Seeds',
    saveAndReuseCampaigns: 'Save and reuse campaign configurations and brand styles',
    searchTemplates: 'Search templates...',
    allCategories: 'All categories',
    campaign: 'Campaign',
    productCategory: 'Product category',
    seasonal: 'Seasonal',
    import: 'Import',
    newTemplate: 'New template',
    noTemplatesYet: 'No templates yet',
    createFirstTemplate: 'Create your first template to quickly reuse configurations',
    createTemplate: 'Create template',
    usedTimes: 'Used {count} times',
    useTemplate: 'Use template',
    deleteTemplate: 'Delete template',
    deleteTemplateConfirm: 'Are you sure you want to delete this template? This action cannot be undone.',
    editTemplate: 'Edit template',
    createNewTemplate: 'Create new template',
    configuration: 'Configuration',
    selectModelOptional: 'Select model (optional)',
    noSpecificModel: 'No specific model',
    selectGenderOptional: 'Select gender (optional)',
    noGenderSelected: 'No gender selected',
    customEnvironment: 'Custom environment',
    brandSeed: 'Brand Seed',
    selectSeedOptional: 'Select seed (optional)',
    noSeed: 'No seed',
    useSeedEnvironment: 'Use seed environment',
    customPromptOptional: 'Custom prompt (optional)',
    expertModePrompt: 'Expert mode prompt...',
    update: 'Update',
    saving: 'Saving...',
    unknownModel: 'Unknown model',
    importedCopy: '(Imported)',
    copy: '(Copy)',
    couldNotImport: 'Could not import template. Check that the file is correct.',

    // Upload Garment
    uploadGarmentPage: 'Upload garment',
    addNewGarmentToLibrary: 'Add a new garment to your library',
    orSelectFromYourGarments: 'Or select from your garments',
    selectImage: 'Select image',
    aiAnalyzingGarment: 'AI analyzing garment...',
    suggestingCategoryName: 'Suggesting category and name',
    analysisError: 'Analysis error',
    tryAgain: 'Try again',
    garmentSaved: 'Garment saved!',
    redirectingToGarments: 'Redirecting to your garments...',
    saveGarment: 'Save garment',
    pleaseEnterName: 'Please enter a name for the model',
    errorAtAnalysis: 'Error at analysis',
    aiCouldNotIdentify: 'AI could not identify the garment. Fill in manually.',
    couldNotAnalyze: 'Could not analyze the image. Try again.',

    // Model Generator
    createModelTitle: 'Create model',
    referenceImagesOptional: 'Reference images (Optional)',
    uploadReferenceFaces: 'Upload images of faces or styles to base the model on',
    headshot: 'Headshot',
    generatePreview: 'Generate preview',
    customPromptForModel: 'Custom prompt for specific model look',
    describeModelSpecifically: 'Describe the model as specifically as possible for best results. This will replace the selected attributes above.',
    generationError: 'Generation error: {error}. Try again or check the console for more information.',
    age: 'Age',
    bodyType: 'Body type',
    hairColor: 'Hair color',
    hairStyle: 'Hair style',
    skinTone: 'Skin tone',
    height: 'Height',
    expertMode: 'Expert mode',
    saveModel: 'Save model',
    slim: 'Slim',
    athletic: 'Athletic',
    average: 'Average',
    curvy: 'Curvy',
    plusSize: 'Plus-size',
    blonde: 'Blonde',
    brunette: 'Brunette',
    black: 'Black',
    red: 'Red',
    gray: 'Gray',
    colored: 'Colored',
    fair: 'Fair',
    light: 'Light',
    medium: 'Medium',
    tan: 'Tan',
    dark: 'Dark',
  },
  sv: {
    // Navigation
    dashboard: 'Dashboard',
    generate: 'Generera',
    garments: 'Plagg',
    gallery: 'Galleri',
    models: 'Modeller',
    templates: 'Mallar',
    training: 'Träning',

    // Auth
    login: 'Logga in',
    logout: 'Logga ut',
    upgradePlan: 'Uppgradera plan',

    // Common
    images: 'bilder',
    language: 'Språk',
    save: 'Spara',
    cancel: 'Avbryt',
    delete: 'Ta bort',
    edit: 'Redigera',
    continue: 'Fortsätt',
    download: 'Ladda ner',
    upload: 'Ladda upp',
    loading: 'Laddar',

    // Upload page
    generateProductImage: 'Generera produktbild',
    aiDrivenModelPhotography: 'AI-driven modellfotografering',
    simple: 'Enkel',
    batch: 'Batch',
    style: 'Style',
    expert: 'Expert',
    uploadGarment: 'Ladda upp plagg',
    garmentInformation: 'Plagginformation',
    brandStyle: 'Varumärkesstil',
    selectModel: 'Välj modell',
    selectEnvironment: 'Välj miljö',
    customPrompt: 'Anpassad prompt',
    aiAnalyzing: 'AI analyserar plagget...',
    aiSuggestions: 'AI-förslag',
    name: 'Namn',
    category: 'Kategori',
    brand: 'Varumärke',
    sku: 'SKU / Artikelnummer',
    optional: 'Valfritt',
    selectCategory: 'Välj kategori',
    tops: 'Överdel',
    bottoms: 'Underdel',
    dresses: 'Klänningar',
    outerwear: 'Ytterkläder',
    accessories: 'Accessoarer',
    selectBrandStyle: 'Välj varumärkesstil',
    none: 'Ingen (standard)',
    useEnvironmentFromSeed: 'Använd seedens förvalda miljö',
    gender: 'Kön',
    female: 'Kvinna',
    male: 'Man',
    orSelectSpecificModel: 'Eller välj specifik modell',
    studio: 'Studio',
    studioLighting: 'Studio lighting, ljusgrå bakgrund',
    stockholm: 'Stockholm',
    stockholmStreets: 'Gator i Stockholm',
    custom: 'Valfri',
    describeEnvironment: 'Beskriv miljön',
    generateImage: 'Generera bild',
    saveAsTemplate: 'Spara som mall',

    // Gallery
    noImagesYet: 'Inga bilder genererade ännu',
    uploadGarmentAndGenerate: 'Ladda upp ett plagg och generera din första bild',
    selectMultiple: 'Välj flera',
    selectAll: 'Markera alla',
    deselectAll: 'Avmarkera alla',
    downloadSelected: 'Ladda ner',
    deleteSelected: 'Ta bort',
    generationInfo: 'Genereringsinformation',
    originalGarment: 'Originalplagg',
    generationSettings: 'Genereringsinställningar',
    model: 'Modell',
    environment: 'Miljö',
    promptUsed: 'Använd prompt',
    imageLink: 'Bildlänk',
    editImage: 'Redigera',
    deleteImage: 'Ta bort bild',
    deleteSelectedImages: 'Ta bort valda bilder',
    deleteImageConfirm: 'Är du säker på att du vill ta bort denna bild? Denna åtgärd kan inte ångras.',
    deleteImagesConfirm: 'Är du säker på att du vill ta bort {count} bilder? Denna åtgärd kan inte ångras.',
    selectedOf: '{selected} valda av {total}',
    generatedImages: 'genererade bilder',
    generating: 'Genererar',
    comingSoon: 'Kommer snart...',
    unknownGarment: 'Okänt plagg',
    created: 'Skapad',
    status: 'Status',
    openOriginalImage: 'Öppna originalbild i nytt fönster →',
    garmentsInOutfit: 'Plagg i outfiten',
    styleDescription: 'Stilbeskrivning',
    aiAnalyzingStyleGallery: 'AI analyserar stilen...',
    aiAnalysisProductDescription: 'AI-analys (Produktbeskrivning)',
    copyProductText: 'Kopiera produkttext',
    styleLabel: 'Stil',

    // Dashboard
    onePhotoIn: 'One photo in. Every asset out.',
    createProfessionalImages: 'Skapa professionella modellbilder på sekunder.',
    getStarted: 'Kom igång',
    totalGarments: 'Plagg',
    generated: 'Genererade',
    thisWeek: 'Denna vecka',
    recentGenerated: 'Senaste genererade',
    recentGarments: 'Senaste plagg',
    recentModels: 'Senaste modeller',
    viewAll: 'Visa alla',
    woman: 'Kvinna',
    man: 'Man',
    neutral: 'Neutral',

    // Garments
    myGarments: 'Mina plagg',
    uploadNew: 'Ladda upp nytt',
    searchGarments: 'Sök på namn, märke eller SKU...',
    noGarmentsYet: 'Inga plagg ännu',
    noMatchingGarments: 'Inga matchande plagg',
    tryDifferentSearch: 'Prova en annan sökning',
    uploadFirstGarment: 'Ladda upp ditt första plagg för att komma igång',
    garmentsTotal: 'plagg totalt',
    deleteGarment: 'Ta bort plagg',
    deleteGarmentConfirm: 'Är du säker på att du vill ta bort detta plagg? Denna åtgärd kan inte ångras.',
    information: 'Information',
    garmentInformationTitle: 'Plagginformation',
    aiDescription: 'AI-beskrivning',
    noAiDescription: 'Ingen AI-beskrivning tillgänglig',
    editInformation: 'Redigera information',

    // Models
    modelArchive: 'Modellarkiv',
    savedModels: 'sparade modeller',
    createModel: 'Skapa modell',
    create: 'Skapa',
    yourCreatedModels: 'Dina skapade modeller',
    modelsOf: '{filtered} av {total} modeller',
    filters: 'Filter',
    searchModelName: 'Sök efter modellnamn...',
    all: 'Alla',
    ethnicity: 'Etnicitet',
    caucasian: 'Kaukasisk',
    african: 'Afrikansk',
    asian: 'Asiatisk',
    hispanic: 'Latinamerikansk',
    middleEastern: 'Mellanöstern',
    mixed: 'Blandad',
    noModelsMatch: 'Inga modeller matchar dina filter',
    years: 'år',
    close: 'Stäng',
    deleteModel: 'Ta bort modell',
    deleteModelConfirm: 'Är du säker på att du vill ta bort denna modell? Denna åtgärd kan inte ångras.',

    // AI Styling
    aiStyling: 'AI Styling',
    selectGarmentsManually: 'Välj plagg att kombinera manuellt',
    selectOutfit: 'Välj outfit',
    letAiSuggestCombinations: 'Låt AI föreslå plagg-kombinationer som passar ihop',
    analyzing: 'Analyserar...',
    getSuggestions: 'Få förslag',
    aiWillSuggestOutfits: 'AI kommer att föreslå outfits som matchar denna varumärkesidentitet',
    analyzingYourGarments: 'Analyserar dina plagg...',
    aiCreatingCombinations: 'AI skapar perfekta outfit-kombinationer',
    suggestionsFromAi: 'Förslag från AI:',
    addForCompleteOutfit: 'Lägg till för komplett outfit:',
    outfitSelected: 'Outfit vald:',
    garmentsSelectedGenerateDirectly: 'plagg valda. Generera direkt eller fortsätt till modellval.',
    cancelSelection: 'Avbryt val',
    getNewSuggestions: 'Få nya förslag',
    readyToStartStyling: 'Redo att börja styla?',
    clickGetSuggestionsToAnalyze: 'Klicka på "Få förslag" så analyserar AI dina plagg och skapar perfekta kombinationer',
    addAtLeast2Garments: 'Lägg till minst 2 plagg för att använda AI Stylist',

    // Batch
    selectGarmentsForBatch: 'Välj plagg för batch-generering',
    selectMultipleGarments: 'Välj flera plagg att generera bilder för samtidigt',
    garmentsSelected: 'plagg valda',
    existingBatchJobs: 'Befintliga Batch-jobb',
    createBatchJob: 'Skapa batch-jobb',

    // Description language
    descriptionLanguage: 'Beskrivningsspråk',
    generateInEnglish: 'Generera på engelska',
    generateInSwedish: 'Generera på svenska',

    // Landing page
    aiGeneratedModels: 'AI-genererade modeller',
    forProfessionalEcommerce: 'för professionell e-handel',
    heylookHelpsModern: 'HeyLook hjälper moderna e-handelsföretag skapa autentiska, professionella produktbilder i skala. Ge ditt team kreativ frihet, konsistens och full kontroll.',
    bookDemo: 'Boka demo',
    trustedByLeading: 'Betrodd av ledande e-handelsföretag',
    realBrandsRealResults: 'Riktiga varumärken, riktiga resultat',
    seeHowAiModels: 'Se hur AI-genererade modeller gör skillnad för e-handelsföretag',
    seeTheTransformation: 'Se transformationen',
    fromGarmentToProfessional: 'Från plagg till professionell produktbild på sekunder',
    createYourOwnUniqueModels: 'Skapa dina egna unika modeller',
    generateAiModels: 'Generera AI-modeller som matchar ditt varumärke perfekt. Anpassa ålder, etnicitet, kroppsstil och mer.',
    createYourModels: 'Skapa dina modeller',
    transformPhotoshoots: 'Transformera fotoshoots med AI-modeller',
    createHighQuality: 'Skapa högkvalitativa modebilder med AI-modeller. Polerade resultat, sömlöst arbetsflöde och ett team redo att guida varje steg.',
    spendLessProduceMore: 'Spendera mindre, producera mer',
    createStudioQuality: 'Skapa studiokvalitativa modebilder utan att öka budgeten. AI-modeller ger dig samma professionella look, utan produktionskostnader.',
    lowerProductionCosts: 'Sänk produktionskostnader och spara tusentals kronor med HeyLooks AI',
    fasterToMarket: 'Snabbare lansering på marknaden',
    accelerateProduction: 'Påskynda produktionscykler och leverera nya kollektioner på dagar. Modeteam kan nu uppdatera looks, förnya bilder och röra sig snabbare än någonsin.',
    shorterProduction: 'Kortare produktionstid från 6 veckor till 24 timmar',
    inclusiveFromStart: 'Inkluderande från start',
    showDiversity: 'Visa mångfald med AI-modeller - olika hudtoner, kroppstyper och stilar - så att dina bilder speglar riktiga kunder, överallt.',
    increasedCTR: 'Ökad CTR genom att använda mångfaldiga modeller för att nå fler kunder',
    testimonialQuote: 'Sedan vi började använda HeyLook kan vi äntligen fokusera på kreativitet istället för koordination och arbeta med den sömlösa flexibilitet som modern e-handel kräver.',
    creativeDirector: 'Creative Director, Nordic Fashion',
    timeSavings: 'Tidsbesparning',
    higherConversion: 'Högre konvertering',
    alwaysAvailable: 'Alltid tillgänglig',
    transformPhotoshootsGetResults: 'Transformera fotoshoots och få felfria resultat på nolltid',
    startCreatingToday: 'Börja skapa professionella AI-genererade produktbilder idag',

    // FileDropzone
    dragAndDropOrClick: 'Dra och släpp eller klicka',
    toSelectImage: 'för att välja en bild',
    takePhotoWithCamera: 'Ta foto med kamera',
    uploading: 'Laddar upp...',

    // Footer
    aiDrivenProductPhotography: 'AI-driven produktfotografering för e-handel',
    product: 'Produkt',
    company: 'Företag',
    aboutUs: 'Om oss',
    contact: 'Kontakt',
    careers: 'Karriär',
    legal: 'Legal',
    privacyPolicy: 'Integritetspolicy',
    termsOfService: 'Användarvillkor',
    cookies: 'Cookies',
    allRightsReserved: 'All rights reserved.',

    // Training
    trainCustomModels: 'Träna egna AI-modeller',
    uploadImagesToTeach: 'Ladda upp bilder för att lära AI specifika poser eller stilar',
    newModel: 'Ny modell',
    poseTraining: 'Pose-träning',
    learnSpecificPoses: 'Lär AI specifika poser genom att ladda upp 5-10 bilder med samma pose',
    styleTraining: 'Stil-träning',
    createConsistentAesthetic: 'Skapa konsekvent estetik med bilder som delar samma visuella stil',
    composition: 'Komposition',
    learnLayoutComposition: 'Lär AI layout och kompositioner från dina referensbilder',
    noTrainedModels: 'Inga tränade modeller ännu',
    createFirstCustomModel: 'Skapa din första anpassade AI-modell',
    trainingImages: 'Träningsbilder',
    uploaded: 'uppladdade',
    clickToSelectImages: 'Klicka för att välja bilder',
    orDragAndDrop: 'eller dra och släpp',
    tipsForBestResults: 'Tips för bästa resultat:',
    useSimilarLighting: 'Använd bilder med liknande ljussättning och kvalitet',
    forPoseTraining: 'För pose-träning: samma pose men olika modeller/kläder',
    forStyleTraining: 'För stil-träning: olika motiv men samma estetik',
    minImagesRecommended: 'Minst 5 bilder rekommenderas, 10+ är optimalt',
    startTraining: 'Starta träning',
    startingTraining: 'Startar träning...',
    useModel: 'Använd modell',
    deleteModelTraining: 'Ta bort modell',
    deleteTrainedModelConfirm: 'Är du säker på att du vill ta bort denna tränade modell? Denna åtgärd kan inte ångras.',
    trainNewModel: 'Träna ny modell',
    type: 'Typ',
    pose: 'Pose',
    description: 'Beskrivning',
    whatShouldLearn: 'Vad ska denna modell lära sig?',
    trainingPromptOptional: 'Träningsprompt (valfritt)',
    atLeast3Recommended: 'minst 3, rekommenderat 5-10',
    moreImages: 'fler bilder',
    uses: 'användningar',

    // Templates
    templatesAndSeeds: 'Mallar & Seeds',
    saveAndReuseCampaigns: 'Spara och återanvänd kampanjkonfigurationer och varumärkesstilar',
    searchTemplates: 'Sök mallar...',
    allCategories: 'Alla kategorier',
    campaign: 'Kampanj',
    productCategory: 'Produktkategori',
    seasonal: 'Säsong',
    import: 'Importera',
    newTemplate: 'Ny mall',
    noTemplatesYet: 'Inga mallar ännu',
    createFirstTemplate: 'Skapa din första mall för att snabbt återanvända konfigurationer',
    createTemplate: 'Skapa mall',
    usedTimes: 'Använd {count} ggr',
    useTemplate: 'Använd mall',
    deleteTemplate: 'Ta bort mall',
    deleteTemplateConfirm: 'Är du säker på att du vill ta bort denna mall? Denna åtgärd kan inte ångras.',
    editTemplate: 'Redigera mall',
    createNewTemplate: 'Skapa ny mall',
    configuration: 'Konfiguration',
    selectModelOptional: 'Välj modell (valfritt)',
    noSpecificModel: 'Ingen specifik modell',
    selectGenderOptional: 'Välj kön (valfritt)',
    noGenderSelected: 'Inget kön valt',
    customEnvironment: 'Anpassad miljö',
    brandSeed: 'Brand Seed',
    selectSeedOptional: 'Välj seed (valfritt)',
    noSeed: 'Ingen seed',
    useSeedEnvironment: 'Använd seedens miljö',
    customPromptOptional: 'Anpassad prompt (valfritt)',
    expertModePrompt: 'Expert-läge prompt...',
    update: 'Uppdatera',
    saving: 'Sparar...',
    unknownModel: 'Okänd modell',
    importedCopy: '(Importerad)',
    copy: '(Kopia)',
    couldNotImport: 'Kunde inte importera mall. Kontrollera att filen är korrekt.',

    // Upload Garment
    uploadGarmentPage: 'Ladda upp plagg',
    addNewGarmentToLibrary: 'Lägg till ett nytt plagg i ditt bibliotek',
    orSelectFromYourGarments: 'Eller välj från dina plagg',
    selectImage: 'Välj bild',
    aiAnalyzingGarment: 'AI analyserar plagget...',
    suggestingCategoryName: 'Föreslår kategori och namn',
    analysisError: 'Fel vid analys',
    tryAgain: 'Försök igen',
    garmentSaved: 'Plagg sparat!',
    redirectingToGarments: 'Omdirigerar till dina plagg...',
    saveGarment: 'Spara plagg',
    pleaseEnterName: 'Vänligen ange ett namn för modellen',
    errorAtAnalysis: 'Fel vid analys',
    aiCouldNotIdentify: 'AI kunde inte identifiera plagget. Fyll i manuellt.',
    couldNotAnalyze: 'Kunde inte analysera bilden. Försök igen.',

    // Model Generator
    createModelTitle: 'Skapa modell',
    referenceImagesOptional: 'Referensbilder (Valfritt)',
    uploadReferenceFaces: 'Ladda upp bilder på ansikten eller stilar att basera modellen på',
    headshot: 'Headshot',
    generatePreview: 'Generera förhandsvisning',
    customPromptForModel: 'Egen prompt för specifik modelllook',
    describeModelSpecifically: 'Beskriv modellen så specifikt som möjligt för bästa resultat. Detta kommer att ersätta de valda attributen ovan.',
    generationError: 'Fel vid generering: {error}. Försök igen eller kontrollera konsolen för mer information.',
    age: 'Ålder',
    bodyType: 'Kroppstyp',
    hairColor: 'Hårfärg',
    hairStyle: 'Hårstil',
    skinTone: 'Hudton',
    height: 'Längd',
    expertMode: 'Expert-läge',
    saveModel: 'Spara modell',
    slim: 'Smal',
    athletic: 'Atletisk',
    average: 'Genomsnittlig',
    curvy: 'Kurvig',
    plusSize: 'Plus-size',
    blonde: 'Blond',
    brunette: 'Brunett',
    black: 'Svart',
    red: 'Röd',
    gray: 'Grå',
    colored: 'Färgat',
    fair: 'Ljus',
    light: 'Mellanljus',
    medium: 'Medium',
    tan: 'Solbränd',
    dark: 'Mörk',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('sv');

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
